Tests us1 review
FSG1/frontend pull request #10
Opened 2017-10-25 11:00 UTC by sjoerdbr

2017-10-27 20:18 UTC, Lehren submitted a review, later dismissed

2017-10-27 20:18 UTC, Lehren commented on src/app/components/module-component/module.component.spec.ts
> +  });*/
Why is this test commented?

2017-10-27 20:18 UTC, Lehren commented on src/app/components/module-overview-component/module-overview.component.spec.ts
> +  });*/
And this one

2017-10-27 20:18 UTC, Lehren commented on src/app/components/skillmatrix-component/skillmatrix.component.spec.ts
> +  // let el:      HTMLElement;
More commented code

2017-10-29 18:35 UTC, NNieuwenhuis commented on src/app/components/skillmatrix-component/skillmatrix.component.spec.ts
>  import {Observable} from 'rxjs/Observable';
is not used

2017-10-29 18:36 UTC, NNieuwenhuis commented on src/app/components/skillmatrix-component/skillmatrix.component.spec.ts
>  import {ModuleContent} from '../../models/modulecontent.model';
is not used

2017-10-29 18:36 UTC, NNieuwenhuis commented on src/app/components/skillmatrix-component/skillmatrix.component.spec.ts
>  import {Subscriber} from 'rxjs/Subscriber';
is not used

2017-10-29 18:36 UTC, NNieuwenhuis commented on src/app/components/skillmatrix-component/skillmatrix.component.spec.ts
>  import {BackendService} from '../../backend.service';
unused import

2017-10-29 18:39 UTC, NNieuwenhuis requested changes
Do you need the comments later? Otherwise delete them please.

2017-10-30 08:26 UTC, sjoerdbr commented on src/app/components/module-component/module.component.spec.ts
> +  });*/
For reference purposes

2017-10-30 09:45 UTC, NNieuwenhuis approved these changes

2017-10-30 09:47 UTC, merged