Edit learning goals
FSG1/frontend pull request #74
Opened 2017-12-14 11:16 UTC by NNieuwenhuis

Problems:
- delete a skill does not work
- design of adding a skill has a strange behaviour
- all dropdowns in adding a skill take the same value

2017-12-14 11:38 UTC, Lehren commented on src/app/components/module-component/edit/module-edit.component.ts
> +  selectedArchtecturalLayer: ArchitecturalLayer;
typo it should ArchitecturalLayer

2017-12-17 13:20 UTC, sjoerdbr approved these changes

2017-12-17 23:10 UTC, lukeelten approved these changes

2017-12-17 23:13 UTC, lukeelten requested changes
Please make proper use of interfaces to not waste performance on runtime.
There is no need to use a class if you do not want to provide functionality inside.

2017-12-17 23:13 UTC, lukeelten commented on src/app/models/studentskill.ts
> +export class StudentSkill {
INTERFACE!!!

2017-12-17 23:13 UTC, lukeelten commented on src/app/models/learninggoal.ts
> +export class LearningGoal {
INTERFACE!!!

2017-12-17 23:13 UTC, lukeelten commented on src/app/models/editmodels/editable_module_output.ts
This should be an interface!!!

2017-12-17 23:13 UTC, lukeelten commented on src/app/models/assesment_part.ts
> +export class AssesmentPart {
INTERFACE!!!!

2017-12-18 12:50 UTC, lukeelten approved these changes

2017-12-19 09:08 UTC, merged